version: '3.9'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-service
    command: gunicorn main:app -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000 -w 4
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    working_dir: /app

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit-app
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
    working_dir: /app
